# Generated by Django 6.0.6 on 2026-06-17 17:55

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdGuardConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='AdGuard Primary', max_length=100)),
                ('url', models.CharField(default='http://192.168.10.1:3000', help_text='URL do AdGuard Home (API)', max_length=255)),
                ('username', models.CharField(default='admin', max_length=100)),
                ('password', models.CharField(default='senha', max_length=100)),
                ('enabled', models.BooleanField(default=False)),
                ('total_queries', models.IntegerField(default=0)),
                ('blocked_queries', models.IntegerField(default=0)),
                ('blocked_percentage', models.FloatField(default=0.0)),
                ('is_active', models.BooleanField(default=False)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Configuração AdGuard',
                'verbose_name_plural': 'Configurações AdGuard',
            },
        ),
        migrations.CreateModel(
            name='NetworkDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mac', models.CharField(help_text='MAC Address do equipamento', max_length=17, unique=True)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('ip', models.CharField(blank=True, max_length=45, null=True)),
                ('model', models.CharField(blank=True, max_length=50, null=True)),
                ('status', models.CharField(default='Desconectado', max_length=50)),
                ('clients', models.IntegerField(default=0, help_text='Número de clientes Wi-Fi conectados')),
                ('last_seen', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Dispositivo Omada',
                'verbose_name_plural': 'Dispositivos Omada',
            },
        ),
        migrations.CreateModel(
            name='OmadaConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(default='https://192.168.10.1:8043', help_text='URL do Omada Controller', max_length=255)),
                ('username', models.CharField(default='admin', max_length=100)),
                ('password', models.CharField(default='senha', max_length=100)),
                ('site_name', models.CharField(default='Default', max_length=100)),
                ('enabled', models.BooleanField(default=False)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Configuração Omada',
                'verbose_name_plural': 'Configurações Omada',
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Nome do serviço (ex: Servidor Proxmox)', max_length=100)),
                ('type', models.CharField(choices=[('ping', 'Ping (ICMP/Subprocess)'), ('tcp', 'Porta TCP'), ('http', 'Requisição HTTP (200 OK)')], default='ping', max_length=10)),
                ('target', models.CharField(help_text='IP, domínio ou URL (ex: 192.168.10.100 ou http://192.168.10.100:8123)', max_length=255)),
                ('port', models.IntegerField(blank=True, help_text='Necessário apenas para conexões TCP (ex: 8006)', null=True)),
                ('enabled', models.BooleanField(default=True)),
                ('is_online', models.BooleanField(default=False)),
                ('latency_ms', models.FloatField(default=0.0, help_text='Tempo de resposta em milissegundos')),
                ('last_checked', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Serviço Monitorado',
                'verbose_name_plural': 'Serviços Monitorados',
            },
        ),
        migrations.CreateModel(
            name='SpeedTestResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('download_mbps', models.FloatField()),
                ('upload_mbps', models.FloatField()),
                ('ping_ms', models.FloatField()),
            ],
            options={
                'verbose_name': 'Resultado Speedtest',
                'verbose_name_plural': 'Resultados Speedtest',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='WANStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gateway_ip', models.CharField(default='192.168.10.1', max_length=45)),
                ('wan_online', models.BooleanField(default=False)),
                ('dns_primary_online', models.BooleanField(default=False)),
                ('dns_secondary_online', models.BooleanField(default=False)),
                ('latency_wan_ms', models.FloatField(default=0.0)),
                ('last_checked', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Status da WAN e DNS',
                'verbose_name_plural': 'Status da WAN e DNS',
            },
        ),
    ]
