# Generated by Django 6.0.6 on 2026-06-17 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WifiNetwork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='SSID da Rede Wi-Fi', max_length=100, unique=True)),
                ('band', models.CharField(default='2.4G / 5G', max_length=50)),
                ('enabled', models.BooleanField(default=True)),
                ('clients', models.IntegerField(default=0)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Rede Wi-Fi',
                'verbose_name_plural': 'Redes Wi-Fi',
            },
        ),
        migrations.AddField(
            model_name='networkdevice',
            name='cpu_util',
            field=models.IntegerField(default=0, help_text='Uso de CPU em %'),
        ),
        migrations.AddField(
            model_name='networkdevice',
            name='mem_util',
            field=models.IntegerField(default=0, help_text='Uso de Memória em %'),
        ),
        migrations.AddField(
            model_name='networkdevice',
            name='temperature',
            field=models.FloatField(default=0.0, help_text='Temperatura do dispositivo em °C'),
        ),
    ]
