# Generated by Django 6.0.6 on 2026-06-17 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0002_wifinetwork_networkdevice_cpu_util_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='omadaconfig',
            name='is_connected',
            field=models.BooleanField(default=False, help_text='Indica se a última sincronização com o Omada foi bem-sucedida'),
        ),
    ]
