# Generated by Django 5.2.10 on 2026-06-17 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0003_omadaconfig_is_connected'),
    ]

    operations = [
        migrations.AddField(
            model_name='wanstatus',
            name='download_rate_mbps',
            field=models.FloatField(default=0.0, help_text='Consumo atual de download em Mbps'),
        ),
        migrations.AddField(
            model_name='wanstatus',
            name='upload_rate_mbps',
            field=models.FloatField(default=0.0, help_text='Consumo atual de upload em Mbps'),
        ),
        migrations.AlterField(
            model_name='adguardconfig',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='networkdevice',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='omadaconfig',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='service',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='speedtestresult',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='wanstatus',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='wifinetwork',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
