# Generated by Django 5.2.10 on 2026-06-18 17:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0004_wanstatus_download_rate_mbps_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OmadaConfig',
        ),
    ]
