# Generated by Django 5.2.10 on 2026-06-19 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0005_delete_omadaconfig'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('speedtest_report_enabled', models.BooleanField(default=False, verbose_name='Relatório Speedtest Ativo')),
                ('speedtest_report_time', models.TimeField(default='08:00', verbose_name='Horário do Relatório')),
                ('last_report_sent_date', models.DateField(blank=True, null=True, verbose_name='Última data em que o relatório foi enviado')),
            ],
            options={
                'verbose_name': 'Configuração do Sistema',
                'verbose_name_plural': 'Configurações do Sistema',
            },
        ),
    ]
